const employees = [
  {
    id: 1,
    firstName: "Rajesh",
    lastName: "Sharma",
    email: "employee1@example.com",
    password: "123",
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Fix Login Bug",
        taskDescription: "Resolve the login issue on mobile devices.",
        taskDate: "2025-05-25",
        category: "development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Update Readme",
        taskDescription: "Improve documentation for new developers.",
        taskDate: "2025-05-15",
        category: "documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Create API Test",
        taskDescription: "Write test cases for payment API.",
        taskDate: "2025-05-28",
        category: "testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Priya",
    lastName: "Verma",
    email: "employee2@example.com",
    password: "123",
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Design Login Page",
        taskDescription: "Create a responsive UI for login page.",
        taskDate: "2025-05-20",
        category: "design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Optimize Images",
        taskDescription: "Reduce image sizes for faster loading.",
        taskDate: "2025-05-18",
        category: "performance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Fix CSS Grid",
        taskDescription: "Resolve grid layout issue on Safari.",
        taskDate: "2025-05-29",
        category: "development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Backup Website",
        taskDescription: "Create full backup before major update.",
        taskDate: "2025-05-30",
        category: "maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Amit",
    lastName: "Patel",
    email: "employee3@example.com",
    password: "123",
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        taskTitle: "Conduct User Interview",
        taskDescription: "Interview 5 users for feedback.",
        taskDate: "2025-05-22",
        category: "research",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Add Dark Mode",
        taskDescription: "Implement theme switcher feature.",
        taskDate: "2025-05-27",
        category: "UI/UX",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Session Timeout",
        taskDescription: "Correct session expiration logic.",
        taskDate: "2025-05-28",
        category: "security",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "Refactor Header",
        taskDescription: "Clean up header component code.",
        taskDate: "2025-05-25",
        category: "development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Iyer",
    email: "employee4@example.com",
    password: "123",
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Setup CI/CD",
        taskDescription: "Integrate Jenkins with GitHub.",
        taskDate: "2025-05-23",
        category: "devops",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Test Registration Flow",
        taskDescription: "Ensure user registration works smoothly.",
        taskDate: "2025-05-21",
        category: "QA",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Fix Broken Links",
        taskDescription: "Remove or update outdated URLs.",
        taskDate: "2025-05-30",
        category: "maintenance",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Karan",
    lastName: "Mehta",
    email: "employee5@example.com",
    password: "123",
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        taskTitle: "Migrate Database",
        taskDescription: "Switch from MySQL to PostgreSQL.",
        taskDate: "2025-05-24",
        category: "database",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Create New Dashboard",
        taskDescription: "Design analytics dashboard.",
        taskDate: "2025-05-20",
        category: "design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Update Privacy Policy",
        taskDescription: "Align privacy docs with new laws.",
        taskDate: "2025-05-19",
        category: "legal",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Fix Email Notification",
        taskDescription: "Emails not sent to users after signup.",
        taskDate: "2025-05-30",
        category: "backend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
